# This workflow will install Python dependencies, create a temporary .env file from .env.example and run main.py
name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        cp .env.example .env
    # Now let's edit "enviorment" to be prod and "secret" to be "github-actions"
    # They're currently empty
    - name: Edit .env file
      run: |
        sed -i 's/ENVIRONMENT=/ENVIRONMENT=prod/g' .env
        sed -i 's/SECRET=/SECRET=github-actions/g' .env
    - name: Run main.py
      run: |
        python main.py